import React, { useState, useEffect } from "react";
import HomeIcon from '@mui/icons-material/Home';
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';


export default function ReturnRefundAndCancellationPolicyComponent(props){
return(
    <div>
      <div style={{background:'#fff',marginTop:20}}>
        <a href='http://localhost:3000/home' style={{textDecoration:'none',color:'#000'}} ><HomeIcon fontSize="medium"/> </a> <ArrowForwardIosIcon fontSize="small"/> <span style={{textAlign:'center',position:'relative',bottom:4,fontSize:13,fontWeight:500}}> Return,Refund and Cancellation Policy</span>
        </div>
         <div style={{display:'flex',justifyContent:'center',alignItems:'center',textAlign:'center',fontSize:30,fontWeight:600,letterSpacing:1,fontFamily:'sans-serif',marginTop:20 }}>
                    The Ultimate Garments
         </div>  
         <div style={{marginTop:20,fontSize:25,fontWeight:600,padding:5}}>
         Return & Exchange Policy
         </div>
         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         The return or exchange can be done within 15 days after your order is delivered.
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         In case the customer received defective/wrong product(s), the reverse pickup will be generated by us and the shipping charges
          will be covered by us only.
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         If the customer's pin code is non-serviceable by our courier partners, then the customer is liable to self-ship the product(s) and
          the shipping charges are 100% refundable if you received defective/wrong product(s).
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         If there is any size issue/wrong product(s) placed by the customer, then he/she has to bear the shipping cost.
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         Kindly pack the product(s) properly to prevent damage during transit. Please ensure the product(s) must be in unused condition with
          all tags and packaging.
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         Due to hygiene concerns of our customers, we do not accept return/refund or perform an exchange for the Boxer Shorts.
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         <b>Note: </b> We suggest you select <b>'Speed Post'</b> as your courier service rather than using other courier companies. Speed Post is a 
         government-owned entity that operates India's largest postal network and it is totally reliable.
         </div>

       

         <div style={{marginTop:20,fontSize:25,fontWeight:600,padding:5}}>
         Refund Policy
         </div>
         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
        <b> For Prepaid Orders:</b> The refund for the COD order is processed within 7 working days after receiving your order and Quality Check
          process. The refunded amount will be reflected in the respective payment mode.
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         <b>For COD Orders:</b> The refund for the COD order is processed within 15 working days after receiving your order and Quality Check 
         process. The refunded amount will be reflected in your selected mode of payment (Gpay account/UPI ID).
         </div>

         <div style={{marginTop:20,fontSize:25,fontWeight:600,padding:5}}>
         Cancellation Policy
         </div>
         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         The cancellation request for your order can be done within 24 hours of placing the order through the Tug Chatbot.
         </div>

         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         If the order is shipped from the warehouse, it cannot be canceled. However, if the product(s) is found to be wrong/damaged,
          you can raise a return request within 15 days of order delivery.
         </div>

         <div style={{marginTop:20,fontSize:25,fontWeight:600,padding:5}}>
         Things To Consider
         </div>
         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         The customers are requested to check the size guide before placing the order.
         </div>
         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         The color of the product(s) may vary as per the customer's screen resolution.
         </div>
         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         Please provide your WhatsApp registered number for timely updates and a better shopping experience.
         </div>
         <div style={{marginTop:3,fontSize:14,fontWeight:500,padding:5,}}>
         Due to hygiene concerns of our customers, we do not accept return/refund or perform an exchange for the Boxer Shorts.
         </div>



    </div>
)

}